version: '2'
services:
  server:
    build: server/.
    networks:
    - net
    ports:
    - "8080:8080"
    environment:
    - database=mysql
    - spring.datasource.url=jdbc:mysql://mysql:3306/petclinic
    - spring.datasource.username=root
    - spring.datasource.password=petclinic
    depends_on:
      - mysql
  client:
    build: client/.
    networks:
    - net
    ports:
    - "3000:3000"
    depends_on:
      - mysql  
  mysql:
    image: mysql:5.7.8
    environment:
    - MYSQL_ROOT_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
    networks:
    - net
networks:
  net: